=== AndreMorais98/4-ano/1ºsemestre/DAW/TPCs/TPC2/pr-2020.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!ELEMENT project_record (meta,workteam,abstract,deliverables,date) >

<!ELEMENT meta (key_name,title,subtitle?,begin_date,end_date,supervisor) >

<!ELEMENT key_name (#PCDATA) >
<!ELEMENT title (#PCDATA) >
<!ELEMENT subtitle (#PCDATA) >
<!ELEMENT begin_date (#PCDATA) >
<!ELEMENT end_date (#PCDATA) >
<!ELEMENT supervisor (#PCDATA) >
<!ATTLIST supervisor url CDATA #REQUIRED>

<!ELEMENT workteam (student)+ >

<!ELEMENT student (id_student,name,email) >
<!ELEMENT id_student (#PCDATA) >
<!ELEMENT name (#PCDATA) >
<!ELEMENT email (#PCDATA) >
<!ATTLIST email url CDATA #REQUIRED >

<!ELEMENT abstract (paragraph)+ >
<!ELEMENT paragraph (#PCDATA | i | u | b | link)* >
<!ELEMENT b (#PCDATA| i | u | link)*>
<!ELEMENT i (#PCDATA| b | u | link)*>
<!ELEMENT u (#PCDATA| b | i | link)*>
<!ELEMENT link (#PCDATA) >
<!ATTLIST link url CDATA #REQUIRED >

<!ELEMENT deliverables (deliverable)* >
<!ELEMENT deliverable (#PCDATA) >
<!ATTLIST deliverable url CDATA #REQUIRED >

<!ELEMENT date (#PCDATA) >

=== AndreMorais98/4-ano/1ºsemestre/DAW/TPCs/TPC2/pr-2020.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE project_record SYSTEM "file:/C:/Users/andre/DAW2020/TPCs/TP2/pr-2020.dtd">
<project_record>
    <meta>
        <key_name>TPC2</key_name>
        <title>XML e DTD</title>
        <subtitle>TPC da UC Desenvolvimento de Aplicações Web</subtitle>
        <begin_date>14/10/2020</begin_date>
        <end_date>21/10/2020</end_date>
        <supervisor url="http://www.di.uminho.pt/~jcr">José Carlos Ramalho</supervisor>
    </meta>
    <workteam>
        <student>
            <id_student>a83899</id_student>
            <name>André Loureiro Morais -</name>
            <email url="mailto:a83899@alunos.uminho.pt">a83899@alunos.uminho.pt</email>
        </student>
    </workteam>
    <abstract>
        <paragraph>O <b>Project Record</b> aqui criado corresponde ao <u>TPC2</u>.</paragraph>
        <paragraph>Primeiramente, foi feito o <u>Documento Type Definition</u> (DTD) e posteriormente gerado um <i>XML</i> que foi populada depois.</paragraph>
        <paragraph>Deixo aqui presente o meu <link url="https://github.com/Demorales1998">Github</link>.</paragraph>
    </abstract>
    <deliverables>
        <deliverable url="pr-2020.dtd">DTD do Project Record (DTD)</deliverable>
    </deliverables>
    <date>24/10/2020</date>
</project_record>
